# Generated by Django 4.2.4 on 2023-08-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(default='0'),
        ),
    ]
